# Backtest config for BTCUSD 1h Binance data

data:
  source: csv
  path: algotrade/data/BTCUSD_1h_Binance.csv

features:
  add_ta: true
  add_returns: true
  add_lags: 2

signal:
  type: bollinger_breakout  # You can change to any implemented signal
  window: 20

position_sizer:
  type: atr
  equity: 10000
  risk_per_trade: 0.01

fee: 0.001
initial_equity: 10000
output: results/btcusd_1h_results.csv
