# Example YAML config for unified backtesting pipeline
# Adjust paths, features, and parameters as needed

data:
  source: csv
  path: data/sample_ohlcv.csv  # Path to your OHLCV CSV file (must have columns: date, open, high, low, close, volume)

features:
  add_ta: true
  add_returns: true
  add_lags: 2

signal:
  type: bollinger_breakout  # Options: sma_crossover, rsi, macd, bollinger_breakout, stochastic, atr_breakout, composite_ma_rsi, ml, dl
  window: 20                # Example param (used by some signals)
  # features: [f1, f2, f3]  # For ML/DL signals: list of feature columns
  # target: target_col      # For ML/DL signals: target column

position_sizer:
  type: atr
  equity: 10000
  risk_per_trade: 0.01

fee: 0.001                  # Commission/slippage per trade
initial_equity: 10000
output: results/example_results.csv
